// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "secret.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDistanceChange();
int distance;

void initProperties(){
  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
