// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "secret.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPitchFChange();
void onRollFChange();
void onLevelChange();
void onSevereLevelChange();

float x, y, z;
float level,roll,pitch,rollF,pitchF=0;
bool severe_level=false;

void initProperties(){

  ArduinoCloud.addProperty(pitchF, READWRITE, ON_CHANGE, onPitchFChange);
  ArduinoCloud.addProperty(rollF, READWRITE, ON_CHANGE, onRollFChange);
  ArduinoCloud.addProperty(level, READWRITE, ON_CHANGE, onLevelChange);
  ArduinoCloud.addProperty(severe_level, READWRITE, ON_CHANGE, onSevereLevelChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
